CFLAGS += -DBOARD_SMARTRF06EB=1

CONTIKI_TARGET_DIRS += srf06

BOARD_SOURCEFILES += board.c VCBinary.c aes256.c base64.c rtc.c board-i2c.c board-spi.c ext-flash.c
BOARD_SOURCEFILES += als-sensor.c

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
