CFLAGS += -DBOARD_SMARTRF06EB=1

CONTIKI_TARGET_DIRS += srf06 common

BOARD_SOURCEFILES += ext-flash.c board-spi.c leds-arch.c srf06-sensors.c button-sensor.c board.c

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
